name: Trigger Zip Arabic Production Build

on:
  push:
    branches: [ production ]
    paths: [ 'arabic/**' ]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: Aspose/apireference.aspose.com
          event-type: build-zip-arabic-production
